
env: flex
runtime: nodejs
env_variables:
  SQL_USER: SA
  SQL_PASSWORD: ziggy11!!
  SQL_DATABASE: aggregator
  INSTANCE_CONNECTION_NAME: asdapi-prod:us-central1:asd-aggragator
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  # INSTANCE_CONNECTION_NAME: asd-api-aggragator:us-central1:asd-aggragator